# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Технотрек АМС-22 и ОС-11
email: n.morev@corp.mail.ru
description: > # this means to ignore newlines until "baseurl:"
    Разработка приложений для iOS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ams22.github.io" # the base hostname & protocol for your site
github_username:  ams22

# Build settings
markdown: kramdown
